services:
  svelte-thing:
    ports:
      - 3000:3000
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://votes:password@postgres:5432/lemmy  
networks:
  default:
    name: lemmy-db
    external: true
